# Étape de base
FROM node:lts-alpine AS base

WORKDIR /app

RUN apk add --no-cache g++ git make curl python3 libc6-compat \
  && corepack enable && corepack prepare pnpm@latest --activate

# Étape pour récupérer les dépendances
FROM base AS dependencies

# Copier les fichiers de configuration nécessaires
COPY package.json pnpm-*.yaml ./
COPY schema/package.json ./schema/package.json
COPY client/package.json ./client/package.json
COPY server/package.json ./server/package.json

# 🚀 Ajout de la copie complète du dossier `schema/` et des autres packages
COPY schema ./schema
COPY client ./client
COPY server ./server

# Installer les dépendances avec `pnpm`
RUN pnpm install --frozen-lockfile

# Étape de build
FROM base AS builder

COPY . .

# Copier les dépendances depuis l'étape "dependencies"
COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=dependencies /app/schema/node_modules ./schema/node_modules
COPY --from=dependencies /app/client/node_modules ./client/node_modules
COPY --from=dependencies /app/server/node_modules ./server/node_modules

ARG TURBO_TOKEN
ENV TURBO_TOKEN=$TURBO_TOKEN

# Build des projets nécessaires
RUN pnpm exec turbo --filter client build

# Étape de production
FROM base AS production

COPY --from=builder /app/package.json /app/pnpm-*.yaml ./
COPY --from=builder /app/client/package.json ./client/package.json

# Installation des dépendances en production
RUN pnpm install --filter client --prod --frozen-lockfile --workspace-root

# Copier les fichiers nécessaires pour l'exécution en production
COPY --from=builder /app/client/.next ./client/.next
COPY --from=builder /app/client/public ./client/public
COPY --from=builder /app/client/next.config.js ./client/next.config.js
COPY --from=builder /app/client/next-i18next.config.js ./client/next-i18next.config.js

EXPOSE 3000

CMD ["pnpm", "start", "--filter", "client"]

