apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    io.kompose.service: app
spec:
  type: NodePort
  selector:
    io.kompose.service: app
  ports:
    - name: http
      port: 3000           # port dans le cluster
      targetPort: 3000     # port dans le conteneur
      nodePort: 30080      # port externe accessible sur chaque node

