# Utilisation de l'image officielle Node.js
FROM mcr.microsoft.com/playwright:v1.36.2-focal

# Définition du répertoire de travail
WORKDIR /app

# Installation des dépendances système requises
RUN apt-get update && apt-get install -y curl build-essential \
  && corepack enable && corepack prepare pnpm@latest --activate

# Copie des fichiers nécessaires pour le build
COPY turbo.json turbo.json
COPY tsconfig.base.json tsconfig.base.json
COPY package.json pnpm-*.yaml ./
COPY schema/package.json ./schema/package.json
COPY server/package.json ./server/package.json
COPY schema ./schema
COPY server ./server

# Installation des dépendances du workspace
RUN pnpm install --no-frozen-lockfile

# Installation de Playwright
RUN pnpm dlx playwright install --with-deps chromium

# 🔥 Vérification des fichiers après la copie
RUN ls -l /app && ls -l /app/schema && ls -l /app/server

# Construction du projet
RUN pnpm exec turbo --filter server build

# Exposition du port pour le serveur
EXPOSE 3100

# Définition du volume pour les exports et uploads
VOLUME /app/server/dist/assets/exports
VOLUME /app/server/dist/assets/uploads

# Définition de l'environnement
ENV PORT=3100

# Démarrage du serveur
CMD ["pnpm", "run", "--filter", "server", "start"]

